const { findConnectionPath } = require('./board-generator')

const { solveBoard } = require('./board-generator')
const PRESET_BOARDS = require('./board-presets')

const ROWS = 12
const COLS = 8
const TOTAL = ROWS * COLS
const TILE_TYPES = 14

const TILE_IMAGE_MAP = [
  '',
  'pattern1r.png',
  'pattern2p.png',
  'pattern3s.png',
  'pattern4g.png',
  'pattern5k.png',
  'pattern6b.png',
  'pattern7w.png',
  'pattern8g.png',
  'pattern9s.png',
  'pattern10p.png',
  'pattern11y.png',
  'pattern12k.png',
  'pattern13r.png',
  'pattern14w.png'
]

const COLOR_SUFFIX_CLASS_MAP = {
  y: 'tile-fill-yellow',
  s: 'tile-fill-blue-soft',
  g: 'tile-fill-green',
  p: 'tile-fill-purple',
  w: 'tile-fill-white',
  r: 'tile-fill-red',
  k: 'tile-fill-pink',
  b: 'tile-fill-blue'
}

const TILE_BORDER_CLASS = TILE_IMAGE_MAP.map((file) => {
  if (!file) return ''
  const match = file.match(/([a-zA-Z])(?=\.[a-zA-Z0-9]+$)/)
  if (!match) return ''
  const suffix = match[1].toLowerCase()
  return COLOR_SUFFIX_CLASS_MAP[suffix] || ''
})

const BOARD_POOL_KEY = 'hard'
const BOARD_POOL_TARGET_SIZE = 5
const BOARD_POOL_RETRY_DELAY = 1000
const BOARD_POOL_WAIT_DELAY = 200
const BOARD_GENERATOR_WORKER_PATH = 'workers/lianliankan-generator.js'
const boardPools = createInitialBoardPools()
const boardPoolRefillTimers = {}
const boardPoolRefilling = {}
const boardPoolPendingRequests = {}
let boardGeneratorWorker = null
let boardGeneratorWorkerAvailable = false
let boardGeneratorWorkerError = ''
let boardGeneratorRequestId = 0

function createInitialBoardPools() {
  const pools = { [BOARD_POOL_KEY]: [] }
  pools[BOARD_POOL_KEY] = (PRESET_BOARDS.hard || [])
    .filter((entry) => isUsableGeneratedBoard(entry && entry.board))
    .map((entry) => cloneBoardEntry(entry))
  return pools
}

function cloneBoardEntry(entry) {
  return {
    seed: entry.seed || 0,
    board: entry.board.map((row) => row.slice())
  }
}

function isUsableGeneratedBoard(board) {
  if (!Array.isArray(board) || board.length !== ROWS) return false

  const counts = {}
  let filled = 0
  for (let r = 0; r < ROWS; r++) {
    const row = board[r]
    if (!Array.isArray(row) || row.length !== COLS) return false
    for (let c = 0; c < COLS; c++) {
      const tile = row[c]
      if (!Number.isInteger(tile) || tile < 1 || tile > TILE_TYPES) return false
      filled += 1
      counts[tile] = (counts[tile] || 0) + 1
    }
  }

  if (filled !== TOTAL) return false
  return Object.keys(counts).every((key) => counts[key] % 2 === 0)
}

function ensureBoardGeneratorWorker() {
  if (boardGeneratorWorker) return boardGeneratorWorker
  if (typeof wx === 'undefined' || typeof wx.createWorker !== 'function') {
    boardGeneratorWorkerAvailable = false
    boardGeneratorWorkerError = 'wx.createWorker unavailable'
    console.warn('[lianliankan] board generator worker unavailable: wx.createWorker is not a function')
    return null
  }

  try {
    boardGeneratorWorker = wx.createWorker(BOARD_GENERATOR_WORKER_PATH)
    boardGeneratorWorkerAvailable = true
    boardGeneratorWorkerError = ''
    console.info('[lianliankan] board generator worker ready')
    boardGeneratorWorker.onMessage((message) => handleBoardGeneratorWorkerMessage(message))
    if (typeof boardGeneratorWorker.onError === 'function') {
      boardGeneratorWorker.onError((error) => {
        boardGeneratorWorkerAvailable = false
        boardGeneratorWorkerError = error && error.message ? error.message : 'worker error'
        console.warn('[lianliankan] board generator worker error', error)
        Object.keys(boardPoolRefilling).forEach((poolKey) => {
          boardPoolRefilling[poolKey] = false
          scheduleBoardPoolRetry(poolKey)
        })
      })
    }
    return boardGeneratorWorker
  } catch (e) {
    boardGeneratorWorker = null
    boardGeneratorWorkerAvailable = false
    boardGeneratorWorkerError = e && e.message ? e.message : 'createWorker failed'
    console.warn('[lianliankan] board generator worker create failed', e)
    return null
  }
}

function handleBoardGeneratorWorkerMessage(message) {
  if (!message || message.type !== 'generatedBoard') return

  const poolKey = boardPoolPendingRequests[message.requestId] || BOARD_POOL_KEY
  delete boardPoolPendingRequests[message.requestId]
  boardPoolRefilling[poolKey] = false

  if (message.ok && isUsableGeneratedBoard(message.board)) {
    const pool = boardPools[poolKey] || []
    boardPools[poolKey] = pool
    if (pool.length < BOARD_POOL_TARGET_SIZE) {
      pool.push({
        seed: message.seed || 0,
        board: message.board
      })
      console.info('[lianliankan] board generated by worker', {
        poolKey,
        poolSize: pool.length,
        seed: message.seed || 0
      })
    }
  } else {
    console.warn('[lianliankan] board generator worker failed', {
      poolKey,
      errorCode: message.errorCode || (message.ok ? 'INVALID_BOARD' : 'UNKNOWN')
    })
  }

  if ((boardPools[poolKey] || []).length < BOARD_POOL_TARGET_SIZE) {
    scheduleBoardPoolRetry(poolKey)
  }
}

function scheduleBoardPoolRetry(poolKey) {
  if (boardPoolRefillTimers[poolKey] || boardPoolRefilling[poolKey]) return
  boardPoolRefillTimers[poolKey] = setTimeout(() => {
    boardPoolRefillTimers[poolKey] = null
    refillBoardPool(poolKey)
  }, BOARD_POOL_RETRY_DELAY)
}

function refillBoardPool(poolKey) {
  const pool = boardPools[poolKey] || []
  boardPools[poolKey] = pool
  if (pool.length >= BOARD_POOL_TARGET_SIZE || boardPoolRefilling[poolKey]) return

  const worker = ensureBoardGeneratorWorker()
  if (!worker) {
    console.warn('[lianliankan] board pool refill skipped: worker unavailable', {
      poolKey,
      error: boardGeneratorWorkerError
    })
    return
  }

  boardPoolRefilling[poolKey] = true
  const requestId = `${poolKey}-${Date.now()}-${boardGeneratorRequestId++}`
  boardPoolPendingRequests[requestId] = poolKey
  try {
    worker.postMessage({ type: 'generateBoard', requestId })
  } catch (e) {
    delete boardPoolPendingRequests[requestId]
    boardPoolRefilling[poolKey] = false
    boardGeneratorWorkerAvailable = false
    boardGeneratorWorkerError = e && e.message ? e.message : 'worker postMessage failed'
    console.warn('[lianliankan] board generator worker postMessage failed', e)
    scheduleBoardPoolRetry(poolKey)
  }
}

function getBoardGeneratorWorkerStatus() {
  return {
    available: boardGeneratorWorkerAvailable,
    error: boardGeneratorWorkerError,
    hasWorker: !!boardGeneratorWorker
  }
}

function takeBoardEntry() {
  const pool = boardPools[BOARD_POOL_KEY] || []
  boardPools[BOARD_POOL_KEY] = pool

  if (pool.length > 0) {
    const index = Math.floor(Math.random() * pool.length)
    const entry = pool.splice(index, 1)[0]
    scheduleBoardPoolRetry(BOARD_POOL_KEY)
    return cloneBoardEntry(entry)
  }

  if (boardPoolRefillTimers[BOARD_POOL_KEY]) {
    clearTimeout(boardPoolRefillTimers[BOARD_POOL_KEY])
    boardPoolRefillTimers[BOARD_POOL_KEY] = null
  }
  refillBoardPool(BOARD_POOL_KEY)
  return null
}

function buildShuffledTileAssets() {
  const ids = []
  for (let type = 1; type <= TILE_TYPES; type++) ids.push(type)
  for (let i = ids.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1))
    const tmp = ids[i]
    ids[i] = ids[j]
    ids[j] = tmp
  }

  const tileImages = ['']
  const tileBorderClasses = ['']
  for (let type = 1; type <= TILE_TYPES; type++) {
    const mappedType = ids[type - 1]
    tileImages[type] = TILE_IMAGE_MAP[mappedType]
    tileBorderClasses[type] = TILE_BORDER_CLASS[mappedType]
  }
  return { tileImages, tileBorderClasses }
}

Page({
  data: {
    rows: ROWS,
    cols: COLS,
    board: [],
    selected: { r: -1, c: -1 },
    status: 'ready',
    statusText: '',
    seconds: 0,
    timer: '0:00',
    pairsLeft: 0,
    lineSegments: [],
    tileImages: TILE_IMAGE_MAP,
    tileBorderClasses: TILE_BORDER_CLASS,
    isAnimating: false,
    isFreshBoard: false,
    isAutoSolving: false,
    isSolvingBoard: false,
    solutionSteps: []
  },

  timerId: null,
  lineTimerId: null,
  solveTimerId: null,
  boardWaitTimerId: null,

  onLoad() {
    this.startGame()
  },

  onShow() {
    if (this.data.status === 'playing') this.startTimer()
    if (this.data.status === 'generating' && !this.boardWaitTimerId) this.tryStartGameFromPool()
    if (typeof wx.hideTabBar === 'function') {
      wx.hideTabBar({ animation: false, fail() {} })
    }
  },

  onHide() {
    this.stopTimer()
    this.clearLineTimer()
    this.clearSolveTimer()
    this.clearBoardWaitTimer()
  },

  onUnload() {
    this.stopTimer()
    this.clearLineTimer()
    this.clearSolveTimer()
    this.clearBoardWaitTimer()
  },

  startGame() {
    this.stopTimer()
    this.clearLineTimer()
    this.clearSolveTimer()
    this.clearBoardWaitTimer()
    this.setData({
      board: this.getEmptyBoard(),
      status: 'generating',
      statusText: '正在生成棋盘，请稍等...',
      selected: { r: -1, c: -1 },
      seconds: 0,
      timer: '0:00',
      pairsLeft: 0,
      lineSegments: [],
      isAnimating: false,
      isAutoSolving: false,
      isSolvingBoard: false,
      isFreshBoard: false,
      solutionSteps: []
    })

    if (typeof wx.nextTick === 'function') {
      wx.nextTick(() => this.tryStartGameFromPool())
    } else {
      setTimeout(() => this.tryStartGameFromPool(), 0)
    }
  },

  tryStartGameFromPool() {
    if (this.data.status !== 'generating') return
    this.clearBoardWaitTimer()

    const entry = takeBoardEntry()
    if (!entry) {
      const workerStatus = getBoardGeneratorWorkerStatus()
      this.setData({
        statusText: workerStatus.error ? '棋盘生成器不可用' : '正在准备棋盘，请稍等...'
      })
      this.queueBoardStart(BOARD_POOL_WAIT_DELAY)
      return
    }

    if (!isUsableGeneratedBoard(entry.board)) {
      console.warn('[lianliankan] discarded invalid board entry', {
        seed: entry.seed || 0
      })
      scheduleBoardPoolRetry(BOARD_POOL_KEY)
      this.queueBoardStart(0)
      return
    }

    const tileAssets = buildShuffledTileAssets()
    const board = entry.board
    this.setData({
      board,
      status: 'playing',
      statusText: '',
      selected: { r: -1, c: -1 },
      seconds: 0,
      timer: '0:00',
      tileImages: tileAssets.tileImages,
      tileBorderClasses: tileAssets.tileBorderClasses,
      pairsLeft: this.countPairsLeft(board),
      lineSegments: [],
      isAnimating: false,
      isAutoSolving: false,
      isSolvingBoard: false,
      isFreshBoard: true,
      solutionSteps: []
    })
    this.startTimer()
  },

  queueBoardStart(delay) {
    this.clearBoardWaitTimer()
    this.boardWaitTimerId = setTimeout(() => {
      this.boardWaitTimerId = null
      this.tryStartGameFromPool()
    }, delay)
  },

  getEmptyBoard() {
    return Array.from({ length: ROWS }, () => Array(COLS).fill(0))
  },

  startTimer() {
    this.stopTimer()
    this.timerId = setInterval(() => {
      const next = this.data.seconds + 1
      this.setData({
        seconds: next,
        timer: this.formatTime(next)
      })
    }, 1000)
  },

  stopTimer() {
    if (this.timerId) {
      clearInterval(this.timerId)
      this.timerId = null
    }
  },

  clearLineTimer() {
    if (this.lineTimerId) {
      clearTimeout(this.lineTimerId)
      this.lineTimerId = null
    }
  },

  clearSolveTimer() {
    if (this.solveTimerId) {
      clearTimeout(this.solveTimerId)
      this.solveTimerId = null
    }
  },

  clearBoardWaitTimer() {
    if (this.boardWaitTimerId) {
      clearTimeout(this.boardWaitTimerId)
      this.boardWaitTimerId = null
    }
  },

  formatTime(seconds) {
    const m = Math.floor(seconds / 60)
    const s = seconds % 60
    return `${m}:${s.toString().padStart(2, '0')}`
  },

  cloneBoard(board) {
    return board.map((row) => row.slice())
  },

  countPairsLeft(board) {
    let filled = 0
    for (let r = 0; r < ROWS; r++) {
      for (let c = 0; c < COLS; c++) {
        if (board[r][c] > 0) filled += 1
      }
    }
    return Math.floor(filled / 2)
  },

  onCellTap(e) {
    if (this.data.status !== 'playing' || this.data.isAnimating || this.data.isAutoSolving || this.data.isSolvingBoard) return

    const idx = Number(e.currentTarget.dataset.index)
    const r = Math.floor(idx / this.data.cols)
    const c = idx % this.data.cols
    const board = this.cloneBoard(this.data.board)

    if (board[r][c] === 0) return

    const sel = this.data.selected
    if (sel.r === -1 && sel.c === -1) {
      this.setData({
        selected: { r, c },
        statusText: ''
      })
      return
    }

    if (sel.r === r && sel.c === c) {
      this.setData({
        selected: { r: -1, c: -1 },
        statusText: ''
      })
      return
    }

    const curTile = board[r][c]
    const prevTile = board[sel.r][sel.c]
    const path = this.findConnectionPath(board, sel.r, sel.c, r, c)

    if (prevTile === curTile && path) {
      this.setData({
        isAnimating: true,
        statusText: '',
        selected: { r: -1, c: -1 },
        isFreshBoard: false
      })

      this.showConnectionLine(path)
      this.lineTimerId = setTimeout(() => {
        board[sel.r][sel.c] = 0
        board[r][c] = 0

        const pairsLeft = this.countPairsLeft(board)
        const won = pairsLeft === 0
        this.setData({
          board,
          lineSegments: [],
          selected: { r: -1, c: -1 },
          pairsLeft,
          isAnimating: false,
          status: won ? 'won' : 'playing',
          statusText: won ? '恭喜过关！' : ''
        })
        if (won) this.stopTimer()
      }, 500)
      return
    }

    if (prevTile !== curTile) {
      this.setData({
        selected: { r: -1, c: -1 },
        statusText: '图片不同'
      })
      return
    }

    this.setData({
      selected: { r: -1, c: -1 },
      statusText: '路径不合法'
    })
  },

  showConnectionLine(path) {
    if (!path || path.length < 2) return
    const query = wx.createSelectorQuery().in(this)
    query.select('.board-wrap').boundingClientRect()
    query.selectAll('.cell').boundingClientRect()
    query.exec((res) => {
      const wrapRect = res[0] || {}
      const cells = res[1] || []
      if (cells.length < TOTAL) return

      const boardLeft = wrapRect.left || 0
      const boardTop = wrapRect.top || 0
      const first = cells[0]
      const secondCol = cells[1]
      const secondRow = cells[COLS]

      const stepX = secondCol.left - first.left
      const stepY = secondRow.top - first.top
      const toPixel = (point) => ({
        x: first.left + first.width / 2 + point.c * stepX - boardLeft,
        y: first.top + first.height / 2 + point.r * stepY - boardTop
      })

      const points = path.map((point) => toPixel(point))
      const segments = []
      const half = 2

      for (let i = 0; i < points.length - 1; i++) {
        const a = points[i]
        const b = points[i + 1]
        if (a.x === b.x) {
          const top = Math.min(a.y, b.y)
          const height = Math.abs(a.y - b.y)
          if (height <= 0) continue
          segments.push({
            style: `left:${a.x - half}px; top:${top}px; width:${half * 2}px; height:${height}px;`
          })
        } else if (a.y === b.y) {
          const left = Math.min(a.x, b.x)
          const width = Math.abs(a.x - b.x)
          if (width <= 0) continue
          segments.push({
            style: `left:${left}px; top:${a.y - half}px; width:${width}px; height:${half * 2}px;`
          })
        }
      }

      this.setData({ lineSegments: segments })
    })
  },

  onAnswerTap() {
    if (this.data.isAutoSolving) {
      this.pauseAutoSolve()
      return
    }

    if (this.data.status !== 'playing' || this.data.isSolvingBoard || this.data.pairsLeft <= 0) return

    this.clearSolveTimer()
    this.clearLineTimer()
    this.setData({
      isSolvingBoard: true,
      lineSegments: [],
      selected: { r: -1, c: -1 },
      statusText: '正在求解...'
    }, () => {
      setTimeout(() => this.solveAndPlayCurrentBoard(), 0)
    })
  },

  pauseAutoSolve() {
    this.clearSolveTimer()
    this.clearLineTimer()
    this.setData({
      isAutoSolving: false,
      isAnimating: false,
      lineSegments: [],
      statusText: '已暂停'
    })
  },

  solveAndPlayCurrentBoard() {
    if (!this.data.isSolvingBoard || this.data.status !== 'playing') return

    const board = this.cloneBoard(this.data.board)
    const result = solveBoard(board, { maxMs: 10000, sliceMs: 1000 })

    if (!result.ok) {
      this.setData({
        isSolvingBoard: false,
        isAutoSolving: false,
        solutionSteps: [],
        statusText: result.errorCode === 'SEARCH_LIMIT' ? '求解超时' : '当前棋盘无解'
      })
      return
    }

    if (!result.solutionSteps || result.solutionSteps.length === 0) {
      this.setData({
        isSolvingBoard: false,
        isAutoSolving: false,
        status: 'won',
        statusText: '恭喜过关！'
      })
      this.stopTimer()
      return
    }

    this.setData({
      isSolvingBoard: false,
      isAutoSolving: true,
      isFreshBoard: false,
      solutionSteps: result.solutionSteps,
      statusText: ''
    })
    this.playAnswerStep(board, 0)
  },

  playAnswerStep(board, stepIndex) {
    if (!this.data.isAutoSolving) return

    const steps = this.data.solutionSteps || []
    if (stepIndex >= steps.length) {
      const won = this.countPairsLeft(board) === 0
      this.setData({
        isAutoSolving: false,
        status: won ? 'won' : 'playing',
        statusText: won ? '恭喜过关！' : ''
      })
      if (won) this.stopTimer()
      return
    }

    const step = steps[stepIndex]
    if (!step || !step.a || !step.b) {
      this.clearSolveTimer()
      this.solveTimerId = setTimeout(() => this.playAnswerStep(board, stepIndex + 1), 0)
      return
    }

    const a = step.a
    const b = step.b
    const aType = board[a.r] && board[a.r][a.c]
    const bType = board[b.r] && board[b.r][b.c]
    if (!aType || !bType || aType !== bType) {
      this.clearSolveTimer()
      this.solveTimerId = setTimeout(() => this.playAnswerStep(board, stepIndex + 1), 0)
      return
    }

    const path = Array.isArray(step.path) ? step.path : this.findConnectionPath(board, a.r, a.c, b.r, b.c)
    if (!path) {
      this.clearSolveTimer()
      this.solveTimerId = setTimeout(() => this.playAnswerStep(board, stepIndex + 1), 0)
      return
    }

    this.showConnectionLine(path)
    this.setData({ isAnimating: true })
    this.lineTimerId = setTimeout(() => {
      const nextBoard = this.cloneBoard(board)
      nextBoard[a.r][a.c] = 0
      nextBoard[b.r][b.c] = 0
      const pairsLeft = this.countPairsLeft(nextBoard)
      const won = pairsLeft === 0
      this.setData({
        board: nextBoard,
        lineSegments: [],
        selected: { r: -1, c: -1 },
        pairsLeft,
        isAnimating: false,
        status: won ? 'won' : 'playing'
      })

      if (won) {
        this.stopTimer()
        this.setData({ isAutoSolving: false, statusText: '恭喜过关！' })
        return
      }

      this.clearSolveTimer()
      this.solveTimerId = setTimeout(() => this.playAnswerStep(nextBoard, stepIndex + 1), 0)
    }, 500)
  },

  findConnectionPath(board, r1, c1, r2, c2) {
    return findConnectionPath(board, r1, c1, r2, c2, { rawPath: true })
  }
})
